version: '3'
services:
  react-app:
    image: node:12-alpine
    build: /app
    working_dir: /app
    # ports:
      # - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    command: npm start
  express-server:
    image: node:12-alpine
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production
    command: node index.js
    # ports:
      # - 8080:8080
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app
      - express-server
